### ISSUE TITLE
Feature idea: notcontains

### ISSUE THREAD

**Issue by rhysmeister** [nick-invision/assert-action#2]
With this action I want to do something like the following...

```yaml
      - name: Test that we don't have an index called ttl
        uses: nick-invision/assert-action@v1
        with:
          expected: ttl
          actual: ${{ steps.mongo2.outputs.mongo }}
          comparison: notcontains
```

Basically I want to ensure that the output doesn't contain a value.
